
import argparse
import sys
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Convert binary file to C++ array")
    parser.add_argument("input", help="Input binary file")
    parser.add_argument("output", help="Output C++ source file")
    parser.add_argument("--name", help="Array name", required=True)
    parser.add_argument("--ns", help="Namespace", default=None)
    
    args = parser.parse_args()
    
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input {input_path} not found")
        sys.exit(1)
        
    data = input_path.read_bytes()
    
    lines = []
    lines.append("// Generated by bin2c.py")
    lines.append('#include "../kernel/types.h"')
    lines.append("")
    
    if args.ns:
        lines.append(f"namespace {args.ns} {{")
        
    lines.append(f"    extern const u8 {args.name}[{len(data)}] = {{")
    
    # Chunk data for readability
    chunk_size = 16
    for i in range(0, len(data), chunk_size):
        chunk = data[i:i+chunk_size]
        hex_vals = [f"0x{b:02X}" for b in chunk]
        lines.append("        " + ", ".join(hex_vals) + ",")
        
    lines.append("    };")
    
    # Helper to get pointer
    lines.append(f"    u8* get_chr_pointer() {{ return (u8*){args.name}; }}")

    if args.ns:
        lines.append("}")
        
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding='utf-8')
    print(f"Generated {out_path} ({len(data)} bytes)")

if __name__ == "__main__":
    main()
